# Generated by Django 2.0 on 2018-06-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('rentPrice', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('sex', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=30)),
                ('rate', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('clothID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cloth')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=11111, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
